# Generated by Django 5.2 on 2025-05-06 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('bio', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=64, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artists/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='FilmArtistRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('ACTOR', 'Actor'), ('DIRECTOR', 'Director'), ('WRITER', 'Writer'), ('PRODUCER', 'Producer')], max_length=20)),
                ('character_name', models.CharField(blank=True, max_length=128, null=True)),
                ('order', models.PositiveIntegerField(blank=True, help_text='Sorting order for cast', null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_roles', to='artists.artist')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_roles', to='films.film')),
            ],
            options={
                'unique_together': {('film', 'artist', 'role_type')},
            },
        ),
    ]
